spring:
  application:
   name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/activityservice
      database: activityservice
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Key is usually a String (like an ID)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Value is usually JSON for Microservices
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: true
#      # Reliability settings
#      acks: all
#      retries: 3

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

kafka:
  topic:
    name: activity-events